cnc_product:
   resource: "@CNCProductBundle/Resources/config/routing.yml"
   prefix:   /

cnc_api:
    resource: "@CNCProductBundle/Resources/config/routes_rest.yml"
    type: rest
    prefix:   /api