<?php

namespace CNC\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;


/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends EntityRepository
{
	/**
	 * Obtiene datos del usuario por el login/password entregado
	 *
	 * @param String $user, $password
	 * @return Type
	 */
	
	/*
	public function busquedaUsuario($user, $password){
		return "test";
	}
	*/

}