<?php

namespace CNC\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * LogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogsRepository extends EntityRepository
{
	/**
	 * Obtiene listado de Logs concatenando los keywords por los cuales fueron buscados
	 * Obtiene los 20 registros  más buscados
	 *
	 * @return Array
	 */

	public function obtenerLogs(){
		$em = $this->getEntityManager();
		$conn = $em->getConnection();
		$sql = '
    		SELECT 
			productos_productos_id, 
			COUNT(productos_productos_id) as totalRegistros,
			GROUP_CONCAT(DISTINCT(keyword)) as keywords
			FROM logs
			GROUP BY productos_productos_id
			ORDER BY totalRegistros DESC
			LIMIT 20
		';
		$stmt = $conn->prepare($sql);
		$stmt->execute();
		return $stmt->fetchAll();
	}
	
}
