<?php

namespace CNC\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	/**
	 * Obtiene listado de Product por cadena otorgada
	 *
	 * @param String $data
	 * @return Type
	 */
	public function resultadoBusqueda($data){
		return $this->getEntityManager()
			->createQueryBuilder()
			->select('p.id, p.titulo, p.descripcion')
			->from('CNCProductBundle:Product', 'p')
			->where('p.titulo LIKE :data')
            ->setParameter('data', '%'.(string) $data.'%')
            ->getQuery()
            ->getResult();
	}

}
